services:
  mongo:
    image: mongo:7
    container_name: signtalk-mongo
    ports:
      - "27017:27017"
    volumes:
      - signtalk-mongo-data:/data/db
    restart: unless-stopped

volumes:
  signtalk-mongo-data:
